mod array_fns;
mod buffer_fns;
mod collection_fns;
mod console;
mod date_fns;
mod encoding_fns;
mod error_fns;
mod function_fns;
mod generator_fns;
mod global_fns;
mod helpers;
mod intl_fns;
mod iterator_fns;
mod json_fns;
mod math_fns;
mod number_fns;
mod object_fns;
mod process_fns;
mod promise_fns;
mod proxy_fns;
mod reflect_fns;
mod regexp_fns;
mod string_fns;
mod symbol_fns;
mod typed_array_fns;

use crate::errors::Result;
use crate::objects::Value;
use crate::vm::interpreter::Interpreter;

pub type NativeFn = fn(&mut Interpreter, &Value, &[Value]) -> Result<Value>;

pub static NATIVE_TABLE: &[NativeFn] = &[
    console::native_console_log,
    console::native_console_warn,
    console::native_console_error,
    console::native_console_info,
    object_fns::native_object_keys,
    object_fns::native_object_values,
    object_fns::native_object_entries,
    object_fns::native_object_assign,
    json_fns::native_json_parse,
    json_fns::native_json_stringify,
    global_fns::native_parse_int,
    global_fns::native_parse_float,
    global_fns::native_is_nan,
    global_fns::native_is_finite,
    global_fns::native_set_timeout,
    global_fns::native_set_interval,
    global_fns::native_clear_timeout,
    global_fns::native_clear_interval,
    math_fns::native_math_abs,
    math_fns::native_math_floor,
    math_fns::native_math_ceil,
    math_fns::native_math_round,
    math_fns::native_math_min,
    math_fns::native_math_max,
    math_fns::native_math_random,
    math_fns::native_math_pow,
    math_fns::native_math_sqrt,
    math_fns::native_math_log,
    math_fns::native_math_sin,
    math_fns::native_math_cos,
    math_fns::native_math_tan,
    array_fns::native_array_push,
    array_fns::native_array_pop,
    array_fns::native_array_shift,
    array_fns::native_array_unshift,
    array_fns::native_array_slice,
    array_fns::native_array_splice,
    array_fns::native_array_index_of,
    array_fns::native_array_includes,
    array_fns::native_array_find,
    array_fns::native_array_find_index,
    array_fns::native_array_map,
    array_fns::native_array_filter,
    array_fns::native_array_reduce,
    array_fns::native_array_for_each,
    array_fns::native_array_some,
    array_fns::native_array_every,
    array_fns::native_array_join,
    array_fns::native_array_reverse,
    array_fns::native_array_sort,
    array_fns::native_array_concat,
    array_fns::native_array_flat,
    string_fns::native_string_char_at,
    string_fns::native_string_char_code_at,
    string_fns::native_string_slice,
    string_fns::native_string_substring,
    string_fns::native_string_index_of,
    string_fns::native_string_includes,
    string_fns::native_string_replace,
    string_fns::native_string_split,
    string_fns::native_string_trim,
    string_fns::native_string_to_lower_case,
    string_fns::native_string_to_upper_case,
    string_fns::native_string_starts_with,
    string_fns::native_string_ends_with,
    string_fns::native_string_repeat,
    string_fns::native_string_pad_start,
    string_fns::native_string_pad_end,
    global_fns::native_number_parse_int,
    global_fns::native_number_parse_float,
    global_fns::native_number_is_nan,
    global_fns::native_number_is_finite,
    error_fns::native_error_constructor,
    error_fns::native_type_error_constructor,
    error_fns::native_reference_error_constructor,
    error_fns::native_syntax_error_constructor,
    error_fns::native_range_error_constructor,
    promise_fns::native_promise_constructor,
    promise_fns::native_promise_then,
    promise_fns::native_promise_catch,
    promise_fns::native_promise_finally,
    promise_fns::native_promise_resolve,
    promise_fns::native_promise_reject,
    promise_fns::native_promise_all,
    promise_fns::native_promise_race,
    proxy_fns::native_proxy_constructor,
    reflect_fns::native_reflect_get,
    reflect_fns::native_reflect_set,
    reflect_fns::native_reflect_has,
    reflect_fns::native_reflect_delete_property,
    reflect_fns::native_reflect_apply,
    reflect_fns::native_reflect_construct,
    reflect_fns::native_reflect_own_keys,
    reflect_fns::native_reflect_get_own_property_descriptor,
    reflect_fns::native_reflect_define_property,
    reflect_fns::native_reflect_get_prototype_of,
    reflect_fns::native_reflect_set_prototype_of,
    reflect_fns::native_reflect_is_extensible,
    reflect_fns::native_reflect_prevent_extensions,
    object_fns::native_object_define_property,
    object_fns::native_object_get_own_property_descriptor,
    object_fns::native_object_freeze,
    // TypedArray
    typed_array_fns::native_typed_array_constructor,
    typed_array_fns::native_typed_array_from,
    typed_array_fns::native_typed_array_of,
    typed_array_fns::native_typed_array_get,
    typed_array_fns::native_typed_array_set,
    typed_array_fns::native_typed_array_length,
    typed_array_fns::native_typed_array_byte_length,
    typed_array_fns::native_typed_array_byte_offset,
    typed_array_fns::native_typed_array_subarray,
    typed_array_fns::native_typed_array_slice,
    // Map
    collection_fns::native_map_constructor,
    collection_fns::native_map_get,
    collection_fns::native_map_set,
    collection_fns::native_map_has,
    collection_fns::native_map_delete,
    collection_fns::native_map_clear,
    collection_fns::native_map_size,
    collection_fns::native_map_for_each,
    collection_fns::native_map_keys,
    collection_fns::native_map_values,
    collection_fns::native_map_entries,
    // Set
    collection_fns::native_set_constructor,
    collection_fns::native_set_add,
    collection_fns::native_set_has,
    collection_fns::native_set_delete,
    collection_fns::native_set_clear,
    collection_fns::native_set_size,
    collection_fns::native_set_for_each,
    collection_fns::native_set_values,
    collection_fns::native_set_keys,
    collection_fns::native_set_entries,
    // WeakMap
    collection_fns::native_weakmap_constructor,
    collection_fns::native_weakmap_get,
    collection_fns::native_weakmap_set,
    collection_fns::native_weakmap_has,
    collection_fns::native_weakmap_delete,
    // WeakSet
    collection_fns::native_weakset_constructor,
    collection_fns::native_weakset_add,
    collection_fns::native_weakset_has,
    collection_fns::native_weakset_delete,
    // Generator
    generator_fns::native_generator_next,
    generator_fns::native_generator_return,
    generator_fns::native_generator_throw,
    // Object additional methods
    object_fns::native_object_is,
    object_fns::native_object_prevent_extensions,
    object_fns::native_object_is_extensible,
    object_fns::native_object_is_sealed,
    object_fns::native_object_is_frozen,
    object_fns::native_object_seal,
    // Symbol
    symbol_fns::native_symbol_constructor,
    symbol_fns::native_symbol_for,
    symbol_fns::native_symbol_key_for,
    // Function.prototype
    function_fns::native_function_call,
    function_fns::native_function_apply,
    function_fns::native_function_bind,
    // Array additional methods
    array_fns::native_array_copy_within,
    array_fns::native_array_fill,
    array_fns::native_array_find_last,
    array_fns::native_array_find_last_index,
    array_fns::native_array_flat_map,
    array_fns::native_array_last_index_of,
    array_fns::native_array_is_array,
    array_fns::native_array_from,
    array_fns::native_array_of,
    // Promise additional methods
    promise_fns::native_promise_all_settled,
    promise_fns::native_promise_any,
    promise_fns::native_promise_with_resolvers,
    // BigInt
    number_fns::native_bigint_constructor,
    // Date (170-213)
    date_fns::native_date_constructor,
    date_fns::native_date_now,
    date_fns::native_date_parse,
    date_fns::native_date_utc,
    date_fns::native_date_get_time,
    date_fns::native_date_get_full_year,
    date_fns::native_date_get_month,
    date_fns::native_date_get_date,
    date_fns::native_date_get_day,
    date_fns::native_date_get_hours,
    date_fns::native_date_get_minutes,
    date_fns::native_date_get_seconds,
    date_fns::native_date_get_milliseconds,
    date_fns::native_date_get_timezone_offset,
    date_fns::native_date_get_utc_full_year,
    date_fns::native_date_get_utc_month,
    date_fns::native_date_get_utc_date,
    date_fns::native_date_get_utc_day,
    date_fns::native_date_get_utc_hours,
    date_fns::native_date_get_utc_minutes,
    date_fns::native_date_get_utc_seconds,
    date_fns::native_date_get_utc_milliseconds,
    date_fns::native_date_set_time,
    date_fns::native_date_set_full_year,
    date_fns::native_date_set_month,
    date_fns::native_date_set_date,
    date_fns::native_date_set_hours,
    date_fns::native_date_set_minutes,
    date_fns::native_date_set_seconds,
    date_fns::native_date_set_milliseconds,
    date_fns::native_date_set_utc_full_year,
    date_fns::native_date_set_utc_month,
    date_fns::native_date_set_utc_date,
    date_fns::native_date_set_utc_hours,
    date_fns::native_date_set_utc_minutes,
    date_fns::native_date_set_utc_seconds,
    date_fns::native_date_set_utc_milliseconds,
    date_fns::native_date_to_string,
    date_fns::native_date_to_iso_string,
    date_fns::native_date_to_utc_string,
    date_fns::native_date_to_date_string,
    date_fns::native_date_to_time_string,
    date_fns::native_date_to_json,
    date_fns::native_date_value_of,
    // RegExp (214-227)
    regexp_fns::native_regexp_constructor,
    regexp_fns::native_regexp_test,
    regexp_fns::native_regexp_exec,
    regexp_fns::native_regexp_to_string,
    regexp_fns::native_regexp_source,
    regexp_fns::native_regexp_flags,
    regexp_fns::native_regexp_global,
    regexp_fns::native_regexp_ignore_case,
    regexp_fns::native_regexp_multiline,
    regexp_fns::native_regexp_dot_all,
    regexp_fns::native_regexp_unicode,
    regexp_fns::native_regexp_sticky,
    regexp_fns::native_regexp_last_index,
    // RegExp-aware String methods (228-230)
    regexp_fns::native_string_match,
    regexp_fns::native_string_replace,
    regexp_fns::native_string_search,
    // Iterator helpers (230-235)
    iterator_fns::native_iterator_map,
    iterator_fns::native_iterator_filter,
    iterator_fns::native_iterator_take,
    iterator_fns::native_iterator_drop,
    iterator_fns::native_iterator_for_each,
    iterator_fns::native_iterator_to_array,
    // Array[Symbol.iterator] (236)
    iterator_fns::native_array_iterator,
    // Encoding (237-238)
    encoding_fns::native_atob,
    encoding_fns::native_btoa,
    // Process (239-245)
    process_fns::native_process_exit,
    process_fns::native_process_cwd,
    process_fns::native_process_chdir,
    process_fns::native_process_stdout_write,
    process_fns::native_process_hrtime,
    process_fns::native_process_hrtime_bigint,
    process_fns::native_process_next_tick,
    // Buffer (246-260)
    buffer_fns::native_buffer_constructor,
    buffer_fns::native_buffer_alloc,
    buffer_fns::native_buffer_from,
    buffer_fns::native_buffer_concat,
    buffer_fns::native_buffer_is_buffer,
    buffer_fns::native_buffer_byte_length,
    buffer_fns::native_buffer_to_string,
    buffer_fns::native_buffer_write,
    buffer_fns::native_buffer_slice,
    buffer_fns::native_buffer_copy,
    buffer_fns::native_buffer_fill,
    buffer_fns::native_buffer_compare,
    buffer_fns::native_buffer_equals,
    buffer_fns::native_buffer_index_of,
    // Intl (261-265)
    intl_fns::native_datetime_format_constructor,
    intl_fns::native_number_format_constructor,
    intl_fns::native_datetime_format_format,
    intl_fns::native_datetime_format_format_to_parts,
    intl_fns::native_number_format_format,
];
