mod array_fns;
mod collection_fns;
mod console;
mod error_fns;
mod function_fns;
mod generator_fns;
mod global_fns;
mod helpers;
mod json_fns;
mod math_fns;
mod object_fns;
mod promise_fns;
mod proxy_fns;
mod reflect_fns;
mod string_fns;
mod symbol_fns;
mod typed_array_fns;

use crate::errors::Result;
use crate::objects::Value;
use crate::vm::interpreter::Interpreter;

pub type NativeFn = fn(&mut Interpreter, &Value, &[Value]) -> Result<Value>;

pub static NATIVE_TABLE: &[NativeFn] = &[
    console::native_console_log,
    console::native_console_warn,
    console::native_console_error,
    console::native_console_info,
    object_fns::native_object_keys,
    object_fns::native_object_values,
    object_fns::native_object_entries,
    object_fns::native_object_assign,
    json_fns::native_json_parse,
    json_fns::native_json_stringify,
    global_fns::native_parse_int,
    global_fns::native_parse_float,
    global_fns::native_is_nan,
    global_fns::native_is_finite,
    global_fns::native_set_timeout,
    global_fns::native_set_interval,
    global_fns::native_clear_timeout,
    global_fns::native_clear_interval,
    math_fns::native_math_abs,
    math_fns::native_math_floor,
    math_fns::native_math_ceil,
    math_fns::native_math_round,
    math_fns::native_math_min,
    math_fns::native_math_max,
    math_fns::native_math_random,
    math_fns::native_math_pow,
    math_fns::native_math_sqrt,
    math_fns::native_math_log,
    math_fns::native_math_sin,
    math_fns::native_math_cos,
    math_fns::native_math_tan,
    array_fns::native_array_push,
    array_fns::native_array_pop,
    array_fns::native_array_shift,
    array_fns::native_array_unshift,
    array_fns::native_array_slice,
    array_fns::native_array_splice,
    array_fns::native_array_index_of,
    array_fns::native_array_includes,
    array_fns::native_array_find,
    array_fns::native_array_find_index,
    array_fns::native_array_map,
    array_fns::native_array_filter,
    array_fns::native_array_reduce,
    array_fns::native_array_for_each,
    array_fns::native_array_some,
    array_fns::native_array_every,
    array_fns::native_array_join,
    array_fns::native_array_reverse,
    array_fns::native_array_sort,
    array_fns::native_array_concat,
    array_fns::native_array_flat,
    string_fns::native_string_char_at,
    string_fns::native_string_char_code_at,
    string_fns::native_string_slice,
    string_fns::native_string_substring,
    string_fns::native_string_index_of,
    string_fns::native_string_includes,
    string_fns::native_string_replace,
    string_fns::native_string_split,
    string_fns::native_string_trim,
    string_fns::native_string_to_lower_case,
    string_fns::native_string_to_upper_case,
    string_fns::native_string_starts_with,
    string_fns::native_string_ends_with,
    string_fns::native_string_repeat,
    string_fns::native_string_pad_start,
    string_fns::native_string_pad_end,
    global_fns::native_number_parse_int,
    global_fns::native_number_parse_float,
    global_fns::native_number_is_nan,
    global_fns::native_number_is_finite,
    error_fns::native_error_constructor,
    error_fns::native_type_error_constructor,
    error_fns::native_reference_error_constructor,
    error_fns::native_syntax_error_constructor,
    error_fns::native_range_error_constructor,
    promise_fns::native_promise_constructor,
    promise_fns::native_promise_then,
    promise_fns::native_promise_catch,
    promise_fns::native_promise_finally,
    promise_fns::native_promise_resolve,
    promise_fns::native_promise_reject,
    promise_fns::native_promise_all,
    promise_fns::native_promise_race,
    proxy_fns::native_proxy_constructor,
    reflect_fns::native_reflect_get,
    reflect_fns::native_reflect_set,
    reflect_fns::native_reflect_has,
    reflect_fns::native_reflect_delete_property,
    reflect_fns::native_reflect_apply,
    reflect_fns::native_reflect_construct,
    reflect_fns::native_reflect_own_keys,
    reflect_fns::native_reflect_get_own_property_descriptor,
    reflect_fns::native_reflect_define_property,
    reflect_fns::native_reflect_get_prototype_of,
    reflect_fns::native_reflect_set_prototype_of,
    reflect_fns::native_reflect_is_extensible,
    reflect_fns::native_reflect_prevent_extensions,
    object_fns::native_object_define_property,
    object_fns::native_object_get_own_property_descriptor,
    object_fns::native_object_freeze,
    // TypedArray
    typed_array_fns::native_typed_array_constructor,
    typed_array_fns::native_typed_array_from,
    typed_array_fns::native_typed_array_of,
    typed_array_fns::native_typed_array_get,
    typed_array_fns::native_typed_array_set,
    typed_array_fns::native_typed_array_length,
    typed_array_fns::native_typed_array_byte_length,
    typed_array_fns::native_typed_array_byte_offset,
    typed_array_fns::native_typed_array_subarray,
    typed_array_fns::native_typed_array_slice,
    // Map
    collection_fns::native_map_constructor,
    collection_fns::native_map_get,
    collection_fns::native_map_set,
    collection_fns::native_map_has,
    collection_fns::native_map_delete,
    collection_fns::native_map_clear,
    collection_fns::native_map_size,
    collection_fns::native_map_for_each,
    collection_fns::native_map_keys,
    collection_fns::native_map_values,
    collection_fns::native_map_entries,
    // Set
    collection_fns::native_set_constructor,
    collection_fns::native_set_add,
    collection_fns::native_set_has,
    collection_fns::native_set_delete,
    collection_fns::native_set_clear,
    collection_fns::native_set_size,
    collection_fns::native_set_for_each,
    collection_fns::native_set_values,
    collection_fns::native_set_keys,
    collection_fns::native_set_entries,
    // WeakMap
    collection_fns::native_weakmap_constructor,
    collection_fns::native_weakmap_get,
    collection_fns::native_weakmap_set,
    collection_fns::native_weakmap_has,
    collection_fns::native_weakmap_delete,
    // WeakSet
    collection_fns::native_weakset_constructor,
    collection_fns::native_weakset_add,
    collection_fns::native_weakset_has,
    collection_fns::native_weakset_delete,
    // Generator
    generator_fns::native_generator_next,
    generator_fns::native_generator_return,
    generator_fns::native_generator_throw,
    // Object additional methods
    object_fns::native_object_is,
    object_fns::native_object_prevent_extensions,
    object_fns::native_object_is_extensible,
    object_fns::native_object_is_sealed,
    object_fns::native_object_is_frozen,
    object_fns::native_object_seal,
    // Symbol
    symbol_fns::native_symbol_constructor,
    symbol_fns::native_symbol_for,
    symbol_fns::native_symbol_key_for,
    // Function.prototype
    function_fns::native_function_call,
    function_fns::native_function_apply,
    function_fns::native_function_bind,
    // Array additional methods
    array_fns::native_array_copy_within,
    array_fns::native_array_fill,
    array_fns::native_array_find_last,
    array_fns::native_array_find_last_index,
    array_fns::native_array_flat_map,
    array_fns::native_array_last_index_of,
    array_fns::native_array_is_array,
    array_fns::native_array_from,
    array_fns::native_array_of,
    // Promise additional methods
    promise_fns::native_promise_all_settled,
    promise_fns::native_promise_any,
    promise_fns::native_promise_with_resolvers,
];
