#![allow(dead_code)]

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

pub struct DtsEntry {
    pub module_name: String,
    pub functions: Vec<FnDtsEntry>,
}

pub struct FnDtsEntry {
    pub name: String,
    pub signature: String,
}

pub fn generate_dts(entries: &[DtsEntry]) -> String {
    let mut output = String::new();

    for entry in entries {
        output.push_str("// Auto-generated by tails-native-macros\n");
        output.push_str("// Do not edit manually\n\n");

        for func in &entry.functions {
            output.push_str(&format!("{}\n", func.signature));
        }
    }

    output
}

pub fn collect_dts_metadata() -> TokenStream {
    quote! {
        pub fn __tails_generate_dts() -> String {
            let mut dts = String::new();
            dts.push_str("// Auto-generated by tails-native-macros\n");
            dts.push_str("// Do not edit manually\n\n");
            dts
        }
    }
}

pub fn expand_dts_collector(module_name: &str, fn_signatures: &[(String, String)]) -> TokenStream {
    let entries: Vec<TokenStream> = fn_signatures
        .iter()
        .map(|(name, sig)| {
            quote! {
                functions.push((#name.to_string(), #sig.to_string()));
            }
        })
        .collect();

    let collector_name = format_ident!("__tails_dts_collector_{}", module_name.replace('-', "_"));

    quote! {
        #[doc(hidden)]
        pub fn #collector_name() -> Vec<(String, String)> {
            let mut functions = Vec::new();
            #(#entries)*
            functions
        }
    }
}
